### ISSUE TITLE
Tracking issue for RFC 14

### ISSUE THREAD

**Issue by junaire** [beyondstorage/go-service-gdrive#15]
ref: #14

**Comment by junaire** [comment]
close this via #14

**Comment by Xuanwo** [comment]
The tracking issue should track the whole lifetime about RFC-14, how about close this issue after #13 gets merged?

**Comment by junaire** [comment]
> The tracking issue should track the whole lifetime about RFC-14, how about close this issue after #13 gets merged?

Sorry, got it

**Comment by Xuanwo** [comment]
Implemented in #16
