### ISSUE TITLE
How to authorize gdrive API

### ISSUE THREAD

**Issue by junaire** [beyondstorage/go-service-gdrive#17]
## Background

Recently I'm working on authorizing gdrive API in different ways. This is because I found we can't really authorize it simply via API key.(It succeed, but can't do things like `Write`, `Delete`)

## Ways to authorize

After  a long search, I found there are two ways to do this:
### [Oauth2](https://developers.google.com/drive/api/v3/about-auth)
If we use this, users will have to copy a link from terminal, and paste a secret code from web.
###  JSON Web Token
Though Google claims that:
>Your application must use OAuth 2.0 to authorize requests. No other authorization protocols are supported.

I still found another way to do this from [StackOverFlow](https://stackoverflow.com/questions/23555040/access-google-drive-without-oauth2)

We can generate a JSON file, and initialize the service like `drive.NewService(ctx, option.WithCredentialsFile(jsonFilePath))`

But there comes some problems: We can't access files created in `go-storage`, as they belong to the API account email (`something like api-service-account@yourproject.iam.gserviceaccount.com`)

Maybe there is a way to solve this, see [https://stackoverflow.com/questions/12211859/i-cant-see-the-files-and-folders-created-via-code-in-my-google-drive](https://stackoverflow.com/questions/12211859/i-cant-see-the-files-and-folders-created-via-code-in-my-google-drive), but it looks very wired. :-(

## Other problems

Now we choose our way to authorize service by using pairs, but it likes we don't have a  protocol for Oauth.

## Summary
- Is it OK to let users copy the link and paste code to the terminal?( It makes hard to test
~~- How to initialize Storager by using OAuth2?( I mean, like `pairs.WithCredential("api:abcdefg")`~~ 
- Do we need support `JSON Web Token`?( Personally I don't want to do this...

**Comment by Xuanwo** [comment]
gcs uses oauth2 too: https://github.com/beyondstorage/go-service-gcs/blob/master/utils.go#L99-L116

Maybe we can use the already authorized token to send API? Let the user decide how to generate the token files. (We can add another tool to help the user finish the job.) 

<blockquote><img src="https://opengraph.githubassets.com/1b7b6bc513c5c9d78ead25e0849e624bf80243ec4e86cc31ba8c26f0ded938f7/beyondstorage/go-service-gcs" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/beyondstorage/go-service-gcs">go-service-gcs/utils.go at master · beyondstorage/go-service-gcs</a></strong></div><div>Google Cloud Storage support for go-storage. Contribute to beyondstorage/go-service-gcs development by creating an account on GitHub.</div></blockquote>

**Comment by junaire** [comment]
> gcs uses oauth2 too: https://github.com/beyondstorage/go-service-gcs/blob/master/utils.go#L99-L116

Sorry but I don't realize we already have examples to do this. Let's update gdrive with what we did in gcs

<blockquote><img src="https://opengraph.githubassets.com/1b7b6bc513c5c9d78ead25e0849e624bf80243ec4e86cc31ba8c26f0ded938f7/beyondstorage/go-service-gcs" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/beyondstorage/go-service-gcs">go-service-gcs/utils.go at master · beyondstorage/go-service-gcs</a></strong></div><div>Google Cloud Storage support for go-storage. Contribute to beyondstorage/go-service-gcs development by creating an account on GitHub.</div></blockquote>

**Comment by Xuanwo** [comment]
Fixed in #18
